import type { DashboardSidebarProject } from "../../types";

const now = new Date();

export const MOCK_SIDEBAR_PROJECTS: DashboardSidebarProject[] = [
	{
		id: "proj-1",
		name: "superset",
		slug: "superset",
		githubRepositoryId: "repo-1",
		githubOwner: "superset-sh",
		githubRepoName: "superset",
		createdAt: now,
		updatedAt: now,
		isCollapsed: false,
		children: [
			{
				type: "workspace",
				workspace: {
					id: "ws-1",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "fix memory leak",
					branch: "fix/renderer-memory-leak",
					pullRequest: {
						url: "https://github.com/superset-sh/superset/pull/3170",
						number: 3170,
						title: "fix: renderer memory leak — 3GB+ heap growth",
						state: "open",
						reviewDecision: "approved",
						checksStatus: "success",
						checks: [
							{ name: "CI", status: "success", url: null },
							{ name: "CodeRabbit", status: "success", url: null },
						],
					},
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
			{
				type: "workspace",
				workspace: {
					id: "ws-2",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "v2 sidebar polish",
					branch: "pr/v2-sidebar-cleanup",
					pullRequest: {
						url: "https://github.com/superset-sh/superset/pull/3503",
						number: 3503,
						title: "feat(desktop): polish v2 sidebar",
						state: "open",
						reviewDecision: null,
						checksStatus: "success",
						checks: [{ name: "CI", status: "success", url: null }],
					},
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 2,
					createdAt: now,
					updatedAt: now,
				},
			},
			{
				type: "workspace",
				workspace: {
					id: "ws-3",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "mcp heartbeat fix",
					branch: "fix/mcp-device-presence",
					pullRequest: {
						url: "https://github.com/superset-sh/superset/pull/3171",
						number: 3171,
						title: "fix(mcp): restore lightweight device presence",
						state: "open",
						reviewDecision: null,
						checksStatus: "success",
						checks: [{ name: "CI", status: "success", url: null }],
					},
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
			{
				type: "workspace",
				workspace: {
					id: "ws-4",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "add theme editor",
					branch: "feat/theme-editor",
					pullRequest: {
						url: "https://github.com/superset-sh/superset/pull/3070",
						number: 3070,
						title: "feat: theme editor",
						state: "draft",
						reviewDecision: null,
						checksStatus: "none",
						checks: [],
					},
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
			{
				type: "workspace",
				workspace: {
					id: "ws-5",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "old refactor",
					branch: "refactor/cleanup",
					pullRequest: {
						url: "https://github.com/superset-sh/superset/pull/2900",
						number: 2900,
						title: "refactor: cleanup old workspace code",
						state: "merged",
						reviewDecision: "approved",
						checksStatus: "success",
						checks: [{ name: "CI", status: "success", url: null }],
					},
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
			{
				type: "workspace",
				workspace: {
					id: "ws-6",
					projectId: "proj-1",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "experiment scroll fix",
					branch: "fix/scroll-jump",
					pullRequest: null,
					repoUrl: "https://github.com/superset-sh/superset",
					branchExistsOnRemote: false,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
		],
	},
	{
		id: "proj-2",
		name: "docs",
		slug: "docs",
		githubRepositoryId: "repo-2",
		githubOwner: "superset-sh",
		githubRepoName: "docs",
		createdAt: now,
		updatedAt: now,
		isCollapsed: false,
		children: [
			{
				type: "workspace",
				workspace: {
					id: "ws-7",
					projectId: "proj-2",
					hostId: "device-1",
					hostType: "local-device",
					accentColor: null,
					name: "update getting started",
					branch: "docs/getting-started",
					pullRequest: {
						url: "https://github.com/superset-sh/docs/pull/42",
						number: 42,
						title: "docs: update getting started guide",
						state: "closed",
						reviewDecision: null,
						checksStatus: "none",
						checks: [],
					},
					repoUrl: "https://github.com/superset-sh/docs",
					branchExistsOnRemote: true,
					previewUrl: null,
					needsRebase: false,
					behindCount: 0,
					createdAt: now,
					updatedAt: now,
				},
			},
		],
	},
];
